from app.models import db, environment, SCHEMA
from sqlalchemy.sql import text
from ..models import Restaurant
from datetime import datetime

def seed_rest():
    # Manually added restaurants
    print(">>>> inside restaurants seeder")
    restaurants = [
        Restaurant(
            owner_id=1,
            name='The Gourmet Kitchen',
            address='123 Culinary Blvd',
            phone_number='5551234567',
            email='info@gourmetkitchen.com',
            description='A modern dining experience with a touch of tradition.',
            banner_img='https://example.com/images/gourmet_kitchen_banner.jpg',
            avg_rating=4.7,
            day_of_week=1,
            open_time=datetime.strptime('2024-08-08 10:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-08 22:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='30-45 mins',
            delivery_fee=4.99
        ),
        Restaurant(
            owner_id=2,
            name='Spice Symphony',
            address='456 Flavor St',
            phone_number='5552345678',
            email='contact@spicesymphony.com',
            description='An orchestra of spices that will tantalize your taste buds.',
            banner_img='https://example.com/images/spice_symphony_banner.jpg',
            avg_rating=4.8,
            day_of_week=2,
            open_time=datetime.strptime('2024-08-09 11:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-09 23:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='25-35 mins',
            delivery_fee=3.99
        ),
        Restaurant(
            owner_id=3,
            name='Pasta Paradise',
            address='789 Italy Ave',
            phone_number='5553456789',
            email='info@pastaparadise.com',
            description='Authentic Italian pasta dishes made from the finest ingredients.',
            banner_img='https://example.com/images/pasta_paradise_banner.jpg',
            avg_rating=4.9,
            day_of_week=3,
            open_time=datetime.strptime('2024-08-10 12:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-10 21:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='20-30 mins',
            delivery_fee=5.49
        ),
        Restaurant(
            owner_id=4,
            name='Sushi World',
            address='123 Tokyo Dr',
            phone_number='5554567890',
            email='info@sushiworld.com',
            description='The freshest sushi outside of Japan.',
            banner_img='https://example.com/images/sushi_world_banner.jpg',
            avg_rating=4.6,
            day_of_week=4,
            open_time=datetime.strptime('2024-08-11 13:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-11 22:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='15-25 mins',
            delivery_fee=2.99
        ),
        Restaurant(
            owner_id=5,
            name='Burger Haven',
            address='456 Burger Ln',
            phone_number='5555678901',
            email='contact@burgerhaven.com',
            description='Juicy burgers with all the fixings.',
            banner_img='https://example.com/images/burger_haven_banner.jpg',
            avg_rating=4.5,
            day_of_week=5,
            open_time=datetime.strptime('2024-08-12 14:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-12 23:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='10-20 mins',
            delivery_fee=3.49
        ),
        Restaurant(
            owner_id=6,
            name='Pizza Palace',
            address='789 Pepperoni Blvd',
            phone_number='5556789012',
            email='info@pizzapalace.com',
            description='New York-style pizza with a crispy crust.',
            banner_img='https://example.com/images/pizza_palace_banner.jpg',
            avg_rating=4.4,
            day_of_week=6,
            open_time=datetime.strptime('2024-08-13 15:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-13 21:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='30-40 mins',
            delivery_fee=4.99
        ),
        Restaurant(
            owner_id=7,
            name='Taco Town',
            address='123 Fiesta St',
            phone_number='5557890123',
            email='contact@tacotown.com',
            description='Tacos so good, you’ll think you’re in Mexico.',
            banner_img='https://example.com/images/taco_town_banner.jpg',
            avg_rating=4.3,
            day_of_week=0,
            open_time=datetime.strptime('2024-08-14 16:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-14 22:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='20-30 mins',
            delivery_fee=2.49
        ),
        Restaurant(
            owner_id=8,
            name='BBQ Barn',
            address='456 Smokehouse Dr',
            phone_number='5558901234',
            email='info@bbqbarn.com',
            description='Slow-cooked BBQ with all the sides.',
            banner_img='https://example.com/images/bbq_barn_banner.jpg',
            avg_rating=4.7,
            day_of_week=1,
            open_time=datetime.strptime('2024-08-15 10:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-15 22:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='40-50 mins',
            delivery_fee=5.99
        ),
        Restaurant(
            owner_id=9,
            name='Salad Stop',
            address='789 Green Blvd',
            phone_number='5559012345',
            email='contact@saladstop.com',
            description='Fresh, healthy salads made to order.',
            banner_img='https://example.com/images/salad_stop_banner.jpg',
            avg_rating=4.6,
            day_of_week=2,
            open_time=datetime.strptime('2024-08-16 11:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-16 21:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='15-25 mins',
            delivery_fee=3.99
        ),
        Restaurant(
            owner_id=10,
            name='Steak House',
            address='123 Grill St',
            phone_number='5550123456',
            email='info@steakhouse.com',
            description='The best steaks in town, cooked to perfection.',
            banner_img='https://example.com/images/steak_house_banner.jpg',
            avg_rating=4.8,
            day_of_week=3,
            open_time=datetime.strptime('2024-08-17 12:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-17 23:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='45-55 mins',
            delivery_fee=6.99
        ),
        Restaurant(
            owner_id=1,
            name='Curry Corner',
            address='456 Spice Rd',
            phone_number='5551234560',
            email='contact@currycorner.com',
            description='Authentic Indian curries that will leave you wanting more.',
            banner_img='https://example.com/images/curry_corner_banner.jpg',
            avg_rating=4.9,
            day_of_week=4,
            open_time=datetime.strptime('2024-08-18 13:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-18 22:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='30-40 mins',
            delivery_fee=4.49
        ),
        Restaurant(
            owner_id=2,
            name='Bagel Bistro',
            address='789 Bagel Ln',
            phone_number='5552345670',
            email='info@bagelbistro.com',
            description='Bagels and coffee to start your day right.',
            banner_img='https://example.com/images/bagel_bistro_banner.jpg',
            avg_rating=4.2,
            day_of_week=5,
            open_time=datetime.strptime('2024-08-19 14:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-19 21:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='20-30 mins',
            delivery_fee=2.99
        ),
        Restaurant(
            owner_id=3,
            name='Soup Stop',
            address='123 Broth St',
            phone_number='5553456780',
            email='contact@soupstop.com',
            description='Hearty soups and fresh bread, just like mom used to make.',
            banner_img='https://example.com/images/soup_stop_banner.jpg',
            avg_rating=4.5,
            day_of_week=6,
            open_time=datetime.strptime('2024-08-20 15:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-20 21:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='25-35 mins',
            delivery_fee=3.49
        ),
        Restaurant(
            owner_id=4,
            name='Wrap World',
            address='456 Roll Ave',
            phone_number='5554567890',
            email='info@wrapworld.com',
            description='Delicious wraps filled with your favorite ingredients.',
            banner_img='https://example.com/images/wrap_world_banner.jpg',
            avg_rating=4.6,
            day_of_week=0,
            open_time=datetime.strptime('2024-08-21 16:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-21 22:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='20-30 mins',
            delivery_fee=2.99
        ),
        Restaurant(
            owner_id=5,
            name='Ramen House',
            address='789 Noodle St',
            phone_number='5555678900',
            email='contact@ramenhouse.com',
            description='Hot, steaming bowls of ramen with all the fixings.',
            banner_img='https://example.com/images/ramen_house_banner.jpg',
            avg_rating=4.7,
            day_of_week=1,
            open_time=datetime.strptime('2024-08-22 10:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-22 22:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='15-25 mins',
            delivery_fee=4.99
        ),
        Restaurant(
            owner_id=6,
            name='Deli Delight',
            address='123 Sandwich Ave',
            phone_number='5556789010',
            email='info@delidelight.com',
            description='Gourmet sandwiches made to order.',
            banner_img='https://example.com/images/deli_delight_banner.jpg',
            avg_rating=4.4,
            day_of_week=2,
            open_time=datetime.strptime('2024-08-23 11:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-23 21:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='20-30 mins',
            delivery_fee=3.49
        ),
        Restaurant(
            owner_id=7,
            name='Bistro Bliss',
            address='456 French Blvd',
            phone_number='5557890120',
            email='contact@bistrobliss.com',
            description='Classic French cuisine with a modern twist.',
            banner_img='https://example.com/images/bistro_bliss_banner.jpg',
            avg_rating=4.8,
            day_of_week=3,
            open_time=datetime.strptime('2024-08-24 12:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-24 23:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='30-40 mins',
            delivery_fee=5.49
        ),
        Restaurant(
            owner_id=8,
            name='Thai Terrace',
            address='789 Spice St',
            phone_number='5558901230',
            email='info@thaiterrace.com',
            description='Authentic Thai food with bold flavors.',
            banner_img='https://example.com/images/thai_terrace_banner.jpg',
            avg_rating=4.9,
            day_of_week=4,
            open_time=datetime.strptime('2024-08-25 13:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-25 22:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='25-35 mins',
            delivery_fee=4.49
        ),
        Restaurant(
            owner_id=9,
            name='Crepe Corner',
            address='123 Dessert Ave',
            phone_number='5559012340',
            email='contact@crepecorner.com',
            description='Sweet and savory crepes made fresh to order.',
            banner_img='https://example.com/images/crepe_corner_banner.jpg',
            avg_rating=4.2,
            day_of_week=5,
            open_time=datetime.strptime('2024-08-26 14:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-26 21:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='20-30 mins',
            delivery_fee=2.99
        ),
        Restaurant(
            owner_id=10,
            name='Fish Fry',
            address='456 Ocean Dr',
            phone_number='5550123450',
            email='info@fishfry.com',
            description='Crispy fried fish with all the sides.',
            banner_img='https://example.com/images/fish_fry_banner.jpg',
            avg_rating=4.7,
            day_of_week=6,
            open_time=datetime.strptime('2024-08-27 15:00:00', '%Y-%m-%d %H:%M:%S'),
            close_time=datetime.strptime('2024-08-27 21:00:00', '%Y-%m-%d %H:%M:%S'),
            delivery_time='25-35 mins',
            delivery_fee=3.99
        ),
    ]

    db.session.bulk_save_objects(restaurants)
    db.session.commit()

def undo_rest():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.restaurants RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM restaurants"))

    db.session.commit()
