from app.models import db, environment, SCHEMA
from sqlalchemy.sql import text
from ..models import Restaurant
from datetime import datetime

def seed_rest():
    restaurant1 = Restaurant(
    id=1,
    owner_id=1,
    name='The Gourmet Kitchen',
    address='123 Culinary Blvd',
    phone_number='5551234567',
    email='info@gourmetkitchen.com',
    description='A modern dining experience with a touch of tradition.',
    banner_img='https://example.com/images/gourmet_kitchen_banner.jpg',
    avg_rating=4.7,
    day_of_week=1,
    open_time=datetime.strptime('2024-08-08 10:00:00', '%Y-%m-%d %H:%M:%S'),
    close_time=datetime.strptime('2024-08-08 22:00:00', '%Y-%m-%d %H:%M:%S'),
    delivery_time='30-45 mins',
    delivery_fee=4.99
)

    db.session.add(restaurant1)
    db.session.commit()

def undo_rest():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.users RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM users"))
        
    db.session.commit()
#     {
#         'id': 2,
#         'owner_id': 2,
#         'name': 'Pizza Paradise',
#         'address': '456 Pizza St',
#         'phone_number': '5552345678',
#         'email': 'contact@pizzaparadise.com',
#         'description': 'The best pizzas in town with fresh ingredients and authentic flavors.',
#         'banner_img': 'https://example.com/images/pizza_paradise_banner.jpg',
#         'avg_rating': 4.5,
#         'day_of_week': 2,
#         'open_time': '2024-08-08 11:00:00',
#         'close_time': '2024-08-08 23:00:00',
#         'delivery_time': '25-35 mins',
#         'delivery_fee': 3.99
#     },
# ]
#     {
#         'id': 3,
#         'owner_id': 3,
#         'name': 'Burger Haven',
#         'address': '789 Burger Lane',
#         'phone_number': '5553456789',
#         'email': 'contact@burgerhaven.com',
#         'description': 'Home of the juiciest burgers with a variety of toppings.',
#         'banner_img': 'https://example.com/images/burger_haven_banner.jpg',
#         'avg_rating': 4.8,
#         'day_of_week': 3,
#         'open_time': '2024-08-08 09:00:00',
#         'close_time': '2024-08-08 21:00:00',
#         'delivery_time': '20-30 mins',
#         'delivery_fee': 2.99
#     },
#     {
#         'id': 4,
#         'owner_id': 4,
#         'name': 'Sushi Zen',
#         'address': '321 Sushi Blvd',
#         'phone_number': '5554567890',
#         'email': 'info@sushizen.com',
#         'description': 'Exquisite sushi rolls made with the freshest ingredients.',
#         'banner_img': 'https://example.com/images/sushi_zen_banner.jpg',
#         'avg_rating': 4.9,
#         'day_of_week': 4,
#         'open_time': '2024-08-08 12:00:00',
#         'close_time': '2024-08-08 22:00:00',
#         'delivery_time': '30-40 mins',
#         'delivery_fee': 3.49
#     },
#     {
#         'id': 5,
#         'owner_id': 5,
#         'name': 'Taco Fiesta',
#         'address': '654 Fiesta Rd',
#         'phone_number': '5555678901',
#         'email': 'info@tacofiesta.com',
#         'description': 'Spicy and flavorful tacos with a variety of fillings.',
#         'banner_img': 'https://example.com/images/taco_fiesta_banner.jpg',
#         'avg_rating': 4.6,
#         'day_of_week': 5,
#         'open_time': '2024-08-08 10:30:00',
#         'close_time': '2024-08-08 21:30:00',
#         'delivery_time': '25-35 mins',
#         'delivery_fee': 3.99
#     },
#     {
#         'id': 6,
#         'owner_id': 6,
#         'name': 'Pasta Palace',
#         'address': '987 Pasta St',
#         'phone_number': '5556789012',
#         'email': 'contact@pastapalace.com',
#         'description': 'Delicious pasta dishes with homemade sauces.',
#         'banner_img': 'https://example.com/images/pasta_palace_banner.jpg',
#         'avg_rating': 4.7,
#         'day_of_week': 6,
#         'open_time': '2024-08-08 11:00:00',
#         'close_time': '2024-08-08 22:30:00',
#         'delivery_time': '30-40 mins',
#         'delivery_fee': 4.49
#     },
#     {
#         'id': 7,
#         'owner_id': 7,
#         'name': 'BBQ Joint',
#         'address': '123 Smoke St',
#         'phone_number': '5557890123',
#         'email': 'info@bbqjoint.com',
#         'description': 'Smoky and savory BBQ with all the fixings.',
#         'banner_img': 'https://example.com/images/bbq_joint_banner.jpg',
#         'avg_rating': 4.8,
#         'day_of_week': 7,
#         'open_time': '2024-08-08 11:30:00',
#         'close_time': '2024-08-08 23:00:00',
#         'delivery_time': '30-45 mins',
#         'delivery_fee': 5.49
#     },
#     {
#         'id': 8,
#         'owner_id': 8,
#         'name': 'Curry House',
#         'address': '456 Spice Rd',
#         'phone_number': '5558901234',
#         'email': 'contact@curryhouse.com',
#         'description': 'Rich and flavorful curries with a variety of spice levels.',
#         'banner_img': 'https://example.com/images/curry_house_banner.jpg',
#         'avg_rating': 4.9,
#         'day_of_week': 1,
#         'open_time': '2024-08-08 10:00:00',
#         'close_time': '2024-08-08 21:00:00',
#         'delivery_time': '25-35 mins',
#         'delivery_fee': 4.99
#     },
#     {
#         'id': 9,
#         'owner_id': 9,
#         'name': 'Noodle Nest',
#         'address': '789 Ramen Blvd',
#         'phone_number': '5559012345',
#         'email': 'info@noodlenest.com',
#         'description': 'Warm and comforting noodle dishes from around the world.',
#         'banner_img': 'https://example.com/images/noodle_nest_banner.jpg',
#         'avg_rating': 4.6,
#         'day_of_week': 2,
#         'open_time': '2024-08-08 11:30:00',
#         'close_time': '2024-08-08 21:30:00',
#         'delivery_time': '20-30 mins',
#         'delivery_fee': 3.99
#     },
#     {
#         'id': 10,
#         'owner_id': 10,
#         'name': 'Steak House',
#         'address': '321 Steak Ave',
#         'phone_number': '5550123456',
#         'email': 'contact@steakhouse.com',
#         'description': 'Juicy steaks cooked to perfection with all the trimmings.',
#         'banner_img': 'https://example.com/images/steak_house_banner.jpg',
#         'avg_rating': 4.9,
#         'day_of_week': 3,
#         'open_time': '2024-08-08 12:00:00',
#         'close_time': '2024-08-08 22:00:00',
#         'delivery_time': '30-40 mins',
#         'delivery_fee': 5.99
#     },
#     {
#         'id': 11,
#         'owner_id': 11,
#         'name': 'Veggie Delight',
#         'address': '654 Green Way',
#         'phone_number': '5551234560',
#         'email': 'info@veggiedelight.com',
#         'description': 'Fresh and healthy vegetarian and vegan dishes.',
#         'banner_img': 'https://example.com/images/veggie_delight_banner.jpg',
#         'avg_rating': 4.8,
#         'day_of_week': 4,
#         'open_time': '2024-08-08 09:30:00',
#         'close_time': '2024-08-08 21:00:00',
#         'delivery_time': '25-35 mins',
#         'delivery_fee': 3.49
#     },
#     {
#         'id': 12,
#         'owner_id': 12,
#         'name': 'Seafood Shack',
#         'address': '987 Ocean Blvd',
#         'phone_number': '5552345670',
#         'email': 'contact@seafoodshack.com',
#         'description': 'Fresh seafood dishes with a coastal flair.',
#         'banner_img': 'https://example.com/images/seafood_shack_banner.jpg',
#         'avg_rating': 4.7,
#         'day_of_week': 5,
#         'open_time': '2024-08-08 10:30:00',
#         'close_time': '2024-08-08 22:00:00',
#         'delivery_time': '30-40 mins',
#         'delivery_fee': 4.99
#     },
#     {
#         'id': 13,
#         'owner_id': 13,
#         'name': 'Dim Sum Delight',
#         'address': '123 Dim Sum Lane',
#         'phone_number': '5553456780',
#         'email': 'info@dimsumdelight.com',
#         'description': 'Delicious dim sum dishes with a variety of flavors.',
#         'banner_img': 'https://example.com/images/dim_sum_delight_banner.jpg',
#         'avg_rating': 4.8,
#         'day_of_week': 6,
#         'open_time': '2024-08-08 10:00:00',
#         'close_time': '2024-08-08 21:00:00',
#         'delivery_time': '25-35 mins',
#         'delivery_fee': 4.49
#     },
#     {
#         'id': 14,
#         'owner_id': 14,
#         'name': 'Indian Spices',
#         'address': '456 Curry Blvd',
#         'phone_number': '5554567890',
#         'email': 'contact@indianspices.com',
#         'description': 'Authentic Indian dishes with a burst of spices.',
#         'banner_img': 'https://example.com/images/indian_spices_banner.jpg',
#         'avg_rating': 4.9,
#         'day_of_week': 7,
#         'open_time': '2024-08-08 11:00:00',
#         'close_time': '2024-08-08 22:30:00',
#         'delivery_time': '30-40 mins',
#         'delivery_fee': 4.99
#     },
#     {
#         'id': 15,
#         'owner_id': 15,
#         'name': 'Mediterranean Grill',
#         'address': '789 Olive St',
#         'phone_number': '5555678900',
#         'email': 'info@mediterraneangrill.com',
#         'description': 'Delicious Mediterranean dishes with fresh ingredients.',
#         'banner_img': 'https://example.com/images/mediterranean_grill_banner.jpg',
#         'avg_rating': 4.8,
#         'day_of_week': 1,
#         'open_time': '2024-08-08 10:30:00',
#         'close_time': '2024-08-08 22:00:00',
#         'delivery_time': '25-35 mins',
#         'delivery_fee': 3.99
#     },
#     {
#         'id': 16,
#         'owner_id': 16,
#         'name': 'Bakery Bliss',
#         'address': '321 Sweet St',
#         'phone_number': '5556789000',
#         'email': 'contact@bakerybliss.com',
#         'description': 'Freshly baked goods and desserts for every occasion.',
#         'banner_img': 'https://example.com/images/bakery_bliss_banner.jpg',
#         'avg_rating': 4.9,
#         'day_of_week': 2,
#         'open_time': '2024-08-08 08:00:00',
#         'close_time': '2024-08-08 18:00:00',
#         'delivery_time': '15-25 mins',
#         'delivery_fee': 2.49
#     },
#     {
#         'id': 17,
#         'owner_id': 17,
#         'name': 'BBQ Pit',
#         'address': '654 Smokehouse Rd',
#         'phone_number': '5557890012',
#         'email': 'info@bbqpit.com',
#         'description': 'Authentic BBQ with smoky flavors and tender meats.',
#         'banner_img': 'https://example.com/images/bbq_pit_banner.jpg',
#         'avg_rating': 4.7,
#         'day_of_week': 3,
#         'open_time': '2024-08-08 11:00:00',
#         'close_time': '2024-08-08 22:00:00',
#         'delivery_time': '30-45 mins',
#         'delivery_fee': 4.99
#     },
#     {
#         'id': 18,
#         'owner_id': 18,
#         'name': 'Pho Real',
#         'address': '987 Noodle St',
#         'phone_number': '5558901230',
#         'email': 'info@phoreal.com',
#         'description': 'Authentic Vietnamese pho with rich broths and fresh ingredients.',
#         'banner_img': 'https://example.com/images/pho_real_banner.jpg',
#         'avg_rating': 4.9,
#         'day_of_week': 4,
#         'open_time': '2024-08-08 09:00:00',
#         'close_time': '2024-08-08 21:00:00',
#         'delivery_time': '20-30 mins',
#         'delivery_fee': 3.99
#     },
#     {
#         'id': 19,
#         'owner_id': 19,
#         'name': 'Tapas Tapas',
#         'address': '321 Fiesta Rd',
#         'phone_number': '5559012340',
#         'email': 'info@tapastapas.com',
#         'description': 'Delicious tapas with a variety of small dishes to share.',
#         'banner_img': 'https://example.com/images/tapas_tapas_banner.jpg',
#         'avg_rating': 4.8,
#         'day_of_week': 5,
#         'open_time': '2024-08-08 12:00:00',
#         'close_time': '2024-08-08 22:00:00',
#         'delivery_time': '25-35 mins',
#         'delivery_fee': 3.49
#     },
#     {
#         'id': 20,
#         'owner_id': 20,
#         'name': 'The Pancake House',
#         'address': '654 Maple Ave',
#         'phone_number': '5550123451',
#         'email': 'contact@pancakehouse.com',
#         'description': 'Fluffy pancakes and delicious breakfast dishes served all day.',
#         'banner_img': 'https://example.com/images/pancake_house_banner.jpg',
#         'avg_rating': 4.7,
#         'day_of_week': 6,
#         'open_time': '2024-08-08 07:00:00',
#         'close_time': '2024-08-08 15:00:00',
#         'delivery_time': '20-30 mins',
#         'delivery_fee': 2.99
#     }
# ]
