from app.models import db, environment, SCHEMA
from sqlalchemy.sql import text
from ..models import Restaurant
from datetime import datetime


def seed_rest():
    # Manually added restaurants
    print(">>>> inside restaurants seeder")
    restaurants = [
        Restaurant(
            owner_id=1,
            name="The Gourmet Kitchen",
            address="123 Culinary Blvd",
            phone_number="5551234567",
            email="info@gourmetkitchen.com",
            description="A modern dining experience with a touch of tradition.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023685/The_Gourmet_Kitchen_xjjphk.png",
            avg_rating=4.7,
            day_of_week=1,
            open_time="10:00",
            close_time="22:00",
            delivery_time="30-45",
            delivery_fee=4.99,
        ),
        Restaurant(
            owner_id=2,
            name="Spice Symphony",
            address="456 Flavor St",
            phone_number="5552345678",
            email="contact@spicesymphony.com",
            description="An orchestra of spices that will tantalize your taste buds.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023665/Spice_Symphony_dbe2ym.png",
            avg_rating=4.8,
            day_of_week=2,
            open_time="10:00",
            close_time="22:00",
            delivery_time="25-35",
            delivery_fee=3.99,
        ),
        Restaurant(
            owner_id=3,
            name="Pasta Paradise",
            address="789 Italy Ave",
            phone_number="5553456789",
            email="info@pastaparadise.com",
            description="Authentic Italian pasta dishes made from the finest ingredients.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023651/Pasta_Paradise_idclgg.png",
            avg_rating=4.9,
            day_of_week=3,
            open_time="10:00",
            close_time="22:00",
            delivery_time="20-30",
            delivery_fee=5.49,
        ),
        Restaurant(
            owner_id=4,
            name="Sushi World",
            address="123 Tokyo Dr",
            phone_number="5554567890",
            email="info@sushiworld.com",
            description="The freshest sushi outside of Japan.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023673/Sushi_World_u5h10g.png",
            avg_rating=4.6,
            day_of_week=4,
            open_time="10:00",
            close_time="22:00",
            delivery_time="15-25",
            delivery_fee=2.99,
        ),
        Restaurant(
            owner_id=5,
            name="Burger Haven",
            address="456 Burger Ln",
            phone_number="5555678901",
            email="contact@burgerhaven.com",
            description="Juicy burgers with all the fixings.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023624/Burger_Haven_nqnvdf.png",
            avg_rating=4.5,
            day_of_week=5,
            open_time="10:00",
            close_time="22:00",
            delivery_time="10-20",
            delivery_fee=3.49,
        ),
        Restaurant(
            owner_id=6,
            name="Pizza Palace",
            address="789 Pepperoni Blvd",
            phone_number="5556789012",
            email="info@pizzapalace.com",
            description="New York-style pizza with a crispy crust.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023655/Pizza_Palace_ypkuom.png",
            avg_rating=4.4,
            day_of_week=6,
            open_time="10:00",
            close_time="22:00",
            delivery_time="30-40",
            delivery_fee=4.99,
        ),
        Restaurant(
            owner_id=7,
            name="Taco Town",
            address="123 Fiesta St",
            phone_number="5557890123",
            email="contact@tacotown.com",
            description="Tacos so good, you’ll think you’re in Mexico.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023677/Taco_Town_yuecrq.png",
            avg_rating=4.3,
            day_of_week=0,
            open_time="10:00",
            close_time="22:00",
            delivery_time="20-30",
            delivery_fee=2.49,
        ),
        Restaurant(
            owner_id=8,
            name="BBQ Barn",
            address="456 Smokehouse Dr",
            phone_number="5558901234",
            email="info@bbqbarn.com",
            description="Slow-cooked BBQ with all the sides.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023621/BBQ_Barn_ncxew0.png",
            avg_rating=4.7,
            day_of_week=1,
            open_time="10:00",
            close_time="22:00",
            delivery_time="40-50",
            delivery_fee=5.99,
        ),
        Restaurant(
            owner_id=9,
            name="Salad Stop",
            address="789 Green Blvd",
            phone_number="5559012345",
            email="contact@saladstop.com",
            description="Fresh, healthy salads made to order.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023662/Salad_Stop_tc4jtt.png",
            avg_rating=4.6,
            day_of_week=2,
            open_time="10:00",
            close_time="22:00",
            delivery_time="15-25",
            delivery_fee=3.99,
        ),
        Restaurant(
            owner_id=10,
            name="Steak House",
            address="123 Grill St",
            phone_number="5550123456",
            email="info@steakhouse.com",
            description="The best steaks in town, cooked to perfection.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023669/Steak_House_esrzgs.png",
            avg_rating=4.8,
            day_of_week=3,
            open_time="10:00",
            close_time="22:00",
            delivery_time="45-55",
            delivery_fee=6.99,
        ),
        Restaurant(
            owner_id=1,
            name="Curry Corner",
            address="456 Spice Rd",
            phone_number="5551234560",
            email="contact@currycorner.com",
            description="Authentic Indian curries that will leave you wanting more.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023627/Curry_Corner_aghnuc.png",
            avg_rating=4.9,
            day_of_week=4,
            open_time="10:00",
            close_time="22:00",
            delivery_time="30-40",
            delivery_fee=4.49,
        ),
        Restaurant(
            owner_id=2,
            name="Maison de Saveurs",
            address="123 Rue de la Cuisine",
            phone_number="5559876543",
            email="info@maisondesaveurs.com",
            description="An exquisite culinary journey through the heart of French cuisine, featuring classic dishes with a modern twist.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023641/Maison_de_Saveurs_irdljk.png",
            avg_rating=4.8,
            day_of_week=5,
            open_time="11:00",
            close_time="23:00",
            delivery_time="30-45",
            delivery_fee=4.99,
        ),

        Restaurant(
            owner_id=3,
            name="Olympian Delights",
            address="456 Agora St",
            phone_number="5556789012",
            email="info@olympiandelights.com",
            description="A culinary celebration of Greek cuisine, offering traditional dishes made with the finest ingredients and a touch of Greek hospitality.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023644/Olympian_Delights_v8g2vs.png",
            avg_rating=4.7,
            day_of_week=7,
            open_time="12:00",
            close_time="22:00",
            delivery_time="25-35",
            delivery_fee=3.99,
        ),

        Restaurant(
            owner_id=4,
            name="Great Wall Gourmet",
            address="789 Dragon Way",
            phone_number="5556789012",
            email="info@greatwallgourmet.com",
            description="Authentic Chinese cuisine with a focus on traditional flavors and modern presentations.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023631/Great_Wall_Gourmet_m516jr.png",
            avg_rating=4.7,
            day_of_week=0,
            open_time="11:00",
            close_time="22:00",
            delivery_time="25-35",
            delivery_fee=3.99,
        ),

        Restaurant(
            owner_id=5,
            name="Ramen House",
            address="789 Noodle St",
            phone_number="5555678900",
            email="contact@ramenhouse.com",
            description="Hot, steaming bowls of ramen with all the fixings.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023658/Ramen_House_uqfsra.png",
            avg_rating=4.7,
            day_of_week=1,
            open_time="10:00",
            close_time="22:00",
            delivery_time="15-25",
            delivery_fee=4.99,
        ),
        Restaurant(
            owner_id=6,
            name="Le Parisian Plate",
            address="456 Parisian Blvd",
            phone_number="5557890123",
            email="info@leparisianplate.com",
            description="A sophisticated blend of French elegance and American comfort, offering a unique culinary experience.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023638/Le_Parisian_Plate_lkhqxy.png",
            avg_rating=4.7,
            day_of_week=1,  # Monday
            open_time="11:00",
            close_time="23:00",
            delivery_time="30-45",
            delivery_fee=4.99,
        ),

        Restaurant(
            owner_id=7,
            name="Athena's Kitchen",
            address="789 Greek Way",
            phone_number="5551234567",
            email="info@athenaskitchen.com",
            description="Experience authentic Greek flavors with a menu inspired by ancient traditions and modern tastes.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023618/Athena_s_Kitchen_rbelpl.png",
            avg_rating=4.7,
            day_of_week=1,  # Assuming it's open on Monday
            open_time="11:00",
            close_time="23:00",
            delivery_time="20-30",
            delivery_fee=4.99,
        ),

        Restaurant(
            owner_id=8,
            name="Thai Terrace",
            address="789 Spice St",
            phone_number="5558901230",
            email="info@thaiterrace.com",
            description="Authentic Thai food with bold flavors.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023681/Thai_Terrace_lypjdm.png",
            avg_rating=4.9,
            day_of_week=4,
            open_time="10:00",
            close_time="22:00",
            delivery_time="25-35",
            delivery_fee=4.49,
        ),
        Restaurant(
            owner_id=9,
            name="Panda Palace Grill",
            address="789 Beijing St",
            phone_number="5551234567",
            email="contact@pandapalacegrill.com",
            description="A delightful fusion of traditional Chinese flavors and American classics.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023648/Panda_Palace_Grill_cfdikt.png",
            avg_rating=4.5,
            day_of_week=1,
            open_time="11:00",
            close_time="23:00",
            delivery_time="30-40",
            delivery_fee=3.99,
        ),

        Restaurant(
            owner_id=10,
            name="Fish Fry",
            address="456 Ocean Dr",
            phone_number="5550123450",
            email="info@fishfry.com",
            description="Crispy fried fish with all the sides.",
            banner_img="https://res.cloudinary.com/dw0k7r34f/image/upload/v1724023634/Fish_Fry_xibxtn.png",
            avg_rating=4.7,
            day_of_week=6,
            open_time="10:00",
            close_time="22:00",
            delivery_time="25-35",
            delivery_fee=3.99,
        ),
    ]

    db.session.bulk_save_objects(restaurants)
    db.session.commit()


def undo_rest():
    if environment == "production":
        db.session.execute(
            f"TRUNCATE table {SCHEMA}.restaurants RESTART IDENTITY CASCADE;"
        )
    else:
        db.session.execute(text("DELETE FROM restaurants"))

    db.session.commit()
