from app.models import db, environment, SCHEMA
from sqlalchemy.sql import text
from ..models import Review
from datetime import datetime, timedelta
import random

def random_date(start, end):
    return start + timedelta(days=random.randint(0, (end - start).days),
                             hours=random.randint(0, 23),
                             minutes=random.randint(0, 59))

start_date = datetime(2018, 1, 1)
end_date = datetime(2024, 8, 10)

def seed_reviews():
    print(">>>> inside reviews seeder")
    reviews = [

        Review(user_id=7, restaurant_id=1, rating=4, comments="The Gourmet Kitchen offers a delightful dining experience. The modern twist on traditional dishes is impressive. I particularly enjoyed the ambience, which made the meal even more enjoyable. The service was attentive and friendly, adding to the overall positive experience.", created_at=random_date(start_date, end_date)),
        Review(user_id=9, restaurant_id=1, rating=5, comments="The food at The Gourmet Kitchen was excellent! The flavors were well-balanced and every dish was a treat. I loved the creative presentation and the freshness of the ingredients. Definitely a place I would visit again.", created_at=random_date(start_date, end_date)),
        Review(user_id=14, restaurant_id=1, rating=3, comments="The Gourmet Kitchen is a decent spot but didn’t live up to the hype. The food was good but not exceptional. I expected more based on the reviews, and the service was a bit slow. It’s okay for an occasional visit.", created_at=random_date(start_date, end_date)),
        Review(user_id=11, restaurant_id=1, rating=2, comments="My experience at The Gourmet Kitchen was underwhelming. The food lacked flavor and the service was mediocre. The ambiance was nice, but it didn’t make up for the poor meal. I wouldn’t recommend it based on my visit.", created_at=random_date(start_date, end_date)),
        Review(user_id=16, restaurant_id=1, rating=4, comments="The Gourmet Kitchen is a great place with a unique menu. The dishes were flavorful and the service was generally good. The atmosphere was pleasant and made for a nice dining experience. I would definitely come back.", created_at=random_date(start_date, end_date)),

        Review(user_id=3, restaurant_id=2, rating=4, comments="Spice Symphony offers an exciting range of spicy dishes. The flavors were bold and the spice levels were just right. The restaurant’s ambiance was lively and added to the overall experience. I enjoyed my meal and would return.", created_at=random_date(start_date, end_date)),
        Review(user_id=5, restaurant_id=2, rating=2, comments="Spice Symphony was not quite what I expected. The spice was overwhelming and some dishes were too hot to enjoy. The service was fine, but the food didn’t impress me. I wouldn’t recommend it for those not used to heavy spices.", created_at=random_date(start_date, end_date)),
        Review(user_id=10, restaurant_id=2, rating=5, comments="Spice Symphony is a must-visit for spice lovers. The dishes were flavorful and had just the right amount of heat. The ambiance was vibrant and the service was attentive. I had a great experience and will definitely be coming back.", created_at=random_date(start_date, end_date)),
        Review(user_id=8, restaurant_id=2, rating=3, comments="Spice Symphony has an interesting menu but some dishes were too spicy for my taste. The flavors were good, but not all were balanced. The environment was lively, though it could be quite noisy. It’s a mixed experience overall.", created_at=random_date(start_date, end_date)),
        Review(user_id=15, restaurant_id=2, rating=4, comments="Spice Symphony is perfect if you enjoy bold flavors. The variety of spices used in the dishes was impressive. The restaurant has a fun atmosphere and the staff is friendly. I enjoyed my visit and would recommend it to others who like spicy food.", created_at=random_date(start_date, end_date)),

        Review(user_id=9, restaurant_id=3, rating=4, comments="Pasta Paradise offers a variety of pasta dishes. The flavors were rich and satisfying, though some dishes were better than others. The restaurant has a warm ambiance and the service was good. Overall, it was a pleasant dining experience.", created_at=random_date(start_date, end_date)),
        Review(user_id=4, restaurant_id=3, rating=5, comments="Pasta Paradise exceeded my expectations. The pasta was cooked perfectly and the sauces were delicious. The restaurant had a cozy atmosphere that made the meal even more enjoyable. I would definitely come back again.", created_at=random_date(start_date, end_date)),
        Review(user_id=12, restaurant_id=3, rating=2, comments="Pasta Paradise was disappointing. The pasta was overcooked and lacked flavor. I was expecting more based on the reviews, but it didn’t meet my expectations. The service was average and didn’t improve the experience.", created_at=random_date(start_date, end_date)),
        Review(user_id=18, restaurant_id=3, rating=3, comments="Pasta Paradise serves decent pasta but nothing extraordinary. The flavors were okay but lacked creativity. The restaurant had a nice ambiance but the food didn’t stand out. It’s an average place for a quick pasta meal.", created_at=random_date(start_date, end_date)),
        Review(user_id=6, restaurant_id=3, rating=4, comments="Pasta Paradise has a good selection of pasta dishes. The food was flavorful and well-prepared. The atmosphere was relaxed and the service was friendly. I enjoyed my meal and will likely return.", created_at=random_date(start_date, end_date)),

        Review(user_id=7, restaurant_id=4, rating=5, comments="Sushi World offers some of the freshest sushi I've had. The variety was impressive and the quality was top-notch. The restaurant’s ambiance was pleasant and the service was excellent. I highly recommend it to sushi lovers.", created_at=random_date(start_date, end_date)),
        Review(user_id=2, restaurant_id=4, rating=3, comments="Sushi World has fresh ingredients, but the sushi lacked finesse. The rolls were simple and didn’t stand out. The restaurant had a nice atmosphere but the food was just average. It’s a decent place if you want basic sushi.", created_at=random_date(start_date, end_date)),
        Review(user_id=14, restaurant_id=4, rating=4, comments="Sushi World provides a satisfying sushi experience. The ingredients were fresh and the flavors were good. The service was friendly and the ambiance was nice. I would recommend it for a casual sushi outing.", created_at=random_date(start_date, end_date)),
        Review(user_id=13, restaurant_id=4, rating=2, comments="Sushi World was underwhelming. The sushi was not as fresh as I hoped and the rolls were uninspired. The service was slow and the restaurant’s atmosphere was average. I wouldn’t return based on my visit.", created_at=random_date(start_date, end_date)),
        Review(user_id=17, restaurant_id=4, rating=5, comments="Sushi World exceeded my expectations. The sushi was fresh and flavorful with creative rolls. The ambiance was upscale and the service was attentive. I had a great dining experience and will definitely be coming back.", created_at=random_date(start_date, end_date)),

        Review(user_id=16, restaurant_id=5, rating=4, comments="Burger Haven is a great spot for burgers. The patties were juicy and the toppings were fresh. The service was friendly and the environment was casual. I enjoyed my meal and would definitely return.", created_at=random_date(start_date, end_date)),
        Review(user_id=12, restaurant_id=5, rating=2, comments="Burger Haven was a disappointment. The burgers were overcooked and the ingredients seemed stale. The fries were soggy and the overall meal was unappetizing. I don’t think I will return.", created_at=random_date(start_date, end_date)),
        Review(user_id=15, restaurant_id=5, rating=3, comments="Burger Haven serves decent burgers but the experience was average. The meat was okay but not exceptional. The restaurant had a nice vibe, but it didn’t impress me overall. It’s a decent place for a quick burger.", created_at=random_date(start_date, end_date)),
        Review(user_id=9, restaurant_id=5, rating=5, comments="Burger Haven has fantastic burgers. The patties were cooked to perfection and the toppings were generous. The service was good and the atmosphere was relaxed. I had a great time and would recommend it to others.", created_at=random_date(start_date, end_date)),
        Review(user_id=11, restaurant_id=5, rating=3, comments="Burger Haven is okay for a burger craving. The food was decent but not outstanding. The environment was casual and the service was average. It’s a good spot for a quick bite but not remarkable.", created_at=random_date(start_date, end_date)),

        Review(user_id=7, restaurant_id=6, rating=4, comments="Pizza Palace has a great variety of pizzas. The crust was crispy and the toppings were plentiful. The service was prompt and the atmosphere was relaxed. I enjoyed my visit and would come back for more.", created_at=random_date(start_date, end_date)),
        Review(user_id=19, restaurant_id=6, rating=5, comments="Pizza Palace is fantastic for pizza lovers. The flavors were bold and the ingredients were fresh. The ambiance was cozy and the service was excellent. It’s a place I would highly recommend.", created_at=random_date(start_date, end_date)),
        Review(user_id=2, restaurant_id=6, rating=3, comments="Pizza Palace offers decent pizza but doesn’t stand out. The crust was a bit too crispy and the toppings were average. The service was fine but the overall experience was just okay. It’s a good spot for a casual pizza meal.", created_at=random_date(start_date, end_date)),
        Review(user_id=15, restaurant_id=6, rating=4, comments="Pizza Palace is a solid choice for pizza. The variety was great and the taste was enjoyable. The restaurant had a good atmosphere and the staff was friendly. I had a pleasant experience and would return.", created_at=random_date(start_date, end_date)),
        Review(user_id=13, restaurant_id=6, rating=2, comments="Pizza Palace did not meet my expectations. The pizza was bland and lacked flavor. The ambiance was nice, but the food didn’t impress me. I wouldn’t recommend it based on my experience.", created_at=random_date(start_date, end_date)),

        Review(user_id=8, restaurant_id=7, rating=5, comments="Taco Town is a great spot for tacos. The variety and quality of the fillings were impressive. The atmosphere was casual and the service was friendly. I thoroughly enjoyed my meal and will definitely be back.", created_at=random_date(start_date, end_date)),
        Review(user_id=17, restaurant_id=7, rating=3, comments="Taco Town has good tacos but some were too bland. The service was fine and the environment was casual. It’s a decent place for tacos but not exceptional. I might return to try different options.", created_at=random_date(start_date, end_date)),
        Review(user_id=4, restaurant_id=7, rating=2, comments="Taco Town was disappointing. The tacos lacked flavor and the fillings were underwhelming. The service was average and the restaurant was not very clean. I don’t think I’ll be coming back.", created_at=random_date(start_date, end_date)),
        Review(user_id=11, restaurant_id=7, rating=4, comments="Taco Town offers a good selection of tacos with fresh ingredients. Some were a bit mild but overall, the taste was good. The staff was friendly and the atmosphere was relaxed. It’s worth checking out if you enjoy tacos.", created_at=random_date(start_date, end_date)),
        Review(user_id=12, restaurant_id=7, rating=5, comments="Taco Town serves some of the best tacos in town. The fillings were flavorful and the tacos were well-made. The restaurant’s vibe was fun and the service was great. I had an excellent experience and will definitely return.", created_at=random_date(start_date, end_date)),

        Review(user_id=14, restaurant_id=8, rating=5, comments="BBQ Barn is a must-visit for BBQ enthusiasts. The meat was tender and flavorful, and the sides were equally impressive. The restaurant has a great atmosphere and the service was attentive. I highly recommend this place for a BBQ fix.", created_at=random_date(start_date, end_date)),
        Review(user_id=19, restaurant_id=8, rating=4, comments="BBQ Barn offers delicious BBQ with a good variety of options. The ribs were particularly tasty and the sides complemented the meal well. The staff was friendly and the environment was casual. A solid choice for BBQ lovers.", created_at=random_date(start_date, end_date)),
        Review(user_id=9, restaurant_id=8, rating=2, comments="BBQ Barn was a letdown. The BBQ was overly charred and lacked flavor. The sides were also underwhelming and the service was slow. I was expecting more based on the reviews.", created_at=random_date(start_date, end_date)),
        Review(user_id=5, restaurant_id=8, rating=4, comments="BBQ Barn is great for a casual BBQ meal. The meat was well-cooked and the sauces were flavorful. The atmosphere was lively and the staff was accommodating. I enjoyed my visit and will likely return.", created_at=random_date(start_date, end_date)),
        Review(user_id=15, restaurant_id=8, rating=3, comments="BBQ Barn has decent BBQ but not the best I’ve had. The flavors were good but the meat was a bit tough. The sides were average and the service was acceptable. It’s a decent spot for BBQ but not outstanding.", created_at=random_date(start_date, end_date)),

        Review(user_id=7, restaurant_id=9, rating=4, comments="Salad Stop is perfect for a light and healthy meal. The salads were fresh and the variety was good. The atmosphere was pleasant and the service was quick. I enjoyed my visit and would recommend it for a healthy option.", created_at=random_date(start_date, end_date)),
        Review(user_id=13, restaurant_id=9, rating=5, comments="Salad Stop offers excellent salads with fresh ingredients. The combinations were creative and satisfying. The restaurant had a bright and welcoming environment. I had a great meal and will definitely come back.", created_at=random_date(start_date, end_date)),
        Review(user_id=20, restaurant_id=9, rating=2, comments="Salad Stop was not what I expected. The salads were bland and lacked flavor. The service was slow and the restaurant was not very clean. I don’t think I will be returning.", created_at=random_date(start_date, end_date)),
        Review(user_id=10, restaurant_id=9, rating=3, comments="Salad Stop provides healthy options but the taste was average. The salads were fresh but lacked excitement. The service was fine and the ambiance was pleasant. It’s an okay place for a quick, healthy meal.", created_at=random_date(start_date, end_date)),
        Review(user_id=6, restaurant_id=9, rating=4, comments="Salad Stop is a great choice for fresh salads. The ingredients were high quality and the portions were generous. The restaurant was clean and the service was friendly. I had a good experience and will return.", created_at=random_date(start_date, end_date)),

        Review(user_id=12, restaurant_id=10, rating=5, comments="Steak House offers an exceptional steak dining experience. The meat was cooked to perfection and the sides were delicious. The service was attentive and the ambiance was upscale. It’s an excellent place for a special occasion.", created_at=random_date(start_date, end_date)),
        Review(user_id=4, restaurant_id=10, rating=3, comments="Steak House serves good steaks but the experience was average. The food was fine but didn’t wow me. The atmosphere was nice but the service was slow. It’s a decent place for steak but not extraordinary.", created_at=random_date(start_date, end_date)),
        Review(user_id=16, restaurant_id=10, rating=4, comments="Steak House is a solid choice for steak lovers. The quality of the meat was high and the cooking was well-done. The ambiance was classy and the service was good. I had a pleasant dining experience.", created_at=random_date(start_date, end_date)),
        Review(user_id=18, restaurant_id=10, rating=2, comments="Steak House was disappointing. The steak was overcooked and lacked flavor. The service was slow and the restaurant didn’t have a great vibe. I wouldn’t recommend it based on my visit.", created_at=random_date(start_date, end_date)),
        Review(user_id=15, restaurant_id=10, rating=4, comments="Steak House is a great spot for a quality steak. The meat was tender and flavorful, and the sides were well-prepared. The service was attentive and the ambiance was upscale. I enjoyed my meal and would come back.", created_at=random_date(start_date, end_date)),

        Review(user_id=13, restaurant_id=11, rating=4, comments="Curry Corner offers a variety of flavorful Indian dishes. The curries were rich and satisfying, though some were spicier than expected. The restaurant had a cozy atmosphere and the service was good. I enjoyed my meal and would visit again.", created_at=random_date(start_date, end_date)),
        Review(user_id=8, restaurant_id=11, rating=5, comments="Curry Corner is fantastic for Indian food. The spices were perfectly balanced and the dishes were full of flavor. The restaurant had a warm and inviting atmosphere. I highly recommend it for anyone craving Indian cuisine.", created_at=random_date(start_date, end_date)),
        Review(user_id=4, restaurant_id=11, rating=2, comments="Curry Corner was a letdown. The curries were bland and lacked depth. The service was slow and the ambiance was not very comfortable. I expected more based on the reviews but won’t be returning.", created_at=random_date(start_date, end_date)),
        Review(user_id=11, restaurant_id=11, rating=3, comments="Curry Corner serves decent Indian food but the experience was average. The dishes were okay but not remarkable. The service was adequate and the atmosphere was pleasant. It’s an average place for Indian cuisine.", created_at=random_date(start_date, end_date)),
        Review(user_id=10, restaurant_id=11, rating=4, comments="Curry Corner provides a good variety of Indian dishes. The flavors were robust and the meal was enjoyable. The restaurant had a nice setting and the service was attentive. I had a positive experience and would return.", created_at=random_date(start_date, end_date)),

        Review(user_id=5, restaurant_id=12, rating=4, comments="Bagel Bistro offers a wide range of delicious bagels. The variety and quality were impressive, though some dishes were better than others. The restaurant had a pleasant atmosphere and the service was good. I enjoyed my visit and will definitely return.", created_at=random_date(start_date, end_date)),
        Review(user_id=17, restaurant_id=12, rating=3, comments="Bagel Bistro has good bagels but some items were average. The variety was nice but some dishes lacked flavor. The service was fine and the restaurant had a decent ambiance. It’s an okay spot for bagels.", created_at=random_date(start_date, end_date)),
        Review(user_id=12, restaurant_id=12, rating=5, comments="Bagel Bistro is fantastic for bagel lovers. The quality of the dishes was high and the flavors were great. The atmosphere was pleasant and the service was efficient. I had an excellent experience and will return.", created_at=random_date(start_date, end_date)),
        Review(user_id=14, restaurant_id=12, rating=2, comments="Bagel Bistro was underwhelming. The bagels were not very flavorful and the service was slow. The restaurant was average and didn’t live up to expectations. I don’t think I will come back.", created_at=random_date(start_date, end_date)),
        Review(user_id=20, restaurant_id=12, rating=4, comments="Bagel Bistro offers a solid bagels experience. The variety and taste of the dishes were good. The ambiance was nice and the service was friendly. I enjoyed my meal and would recommend it.", created_at=random_date(start_date, end_date)),

        Review(user_id=6, restaurant_id=13, rating=5, comments="Soup Stop is a fantastic place for a meal. The menu had a great variety and the food was delicious. The atmosphere was cozy and the service was excellent. I highly recommend this restaurant for a great dining experience.", created_at=random_date(start_date, end_date)),
        Review(user_id=10, restaurant_id=13, rating=4, comments="Soup Stop offers a great dining experience with a varied menu. The food was flavorful and well-presented. The service was good and the ambiance was pleasant. It’s a nice spot for a meal out.", created_at=random_date(start_date, end_date)),
        Review(user_id=16, restaurant_id=13, rating=3, comments="Soup Stop has a good menu but the food was average. Some dishes were better than others and the service was okay. The restaurant had a nice atmosphere but didn’t stand out. It’s a decent place for a casual meal.", created_at=random_date(start_date, end_date)),
        Review(user_id=7, restaurant_id=13, rating=2, comments="Soup Stop was disappointing. The food was bland and the service was slow. The ambiance was nice, but it didn’t make up for the poor meal. I wouldn’t return based on my experience.", created_at=random_date(start_date, end_date)),
        Review(user_id=12, restaurant_id=13, rating=4, comments="Soup Stop offers a pleasant dining experience. The menu had a good variety and the food was well-prepared. The atmosphere was cozy and the service was friendly. I enjoyed my visit and would come back.", created_at=random_date(start_date, end_date)),

        Review(user_id=3, restaurant_id=14, rating=4, comments="Wrap World is a great place for wraps. The wraps were flavorful and the variety was impressive. The atmosphere was relaxed and the service was good. I had a satisfying meal and would return.", created_at=random_date(start_date, end_date)),
        Review(user_id=18, restaurant_id=14, rating=5, comments="Wrap World serves excellent wraps. The flavors were authentic and the food was delicious. The service was prompt and the ambiance was pleasant. It’s a fantastic spot for a wrap craving.", created_at=random_date(start_date, end_date)),
        Review(user_id=5, restaurant_id=14, rating=3, comments="Wrap World is decent but some wraps were average. The variety was good but not all wraps were flavorful. The service was fine and the restaurant had a casual vibe. It’s a good spot for an occasional meal.", created_at=random_date(start_date, end_date)),
        Review(user_id=11, restaurant_id=14, rating=2, comments="Wrap World didn’t meet my expectations. The food was bland and the service was slow. The restaurant’s ambiance was okay but didn’t make up for the lackluster meal. I wouldn’t recommend it based on my visit.", created_at=random_date(start_date, end_date)),
        Review(user_id=9, restaurant_id=14, rating=4, comments="Wrap World provides a good variety of wraps. The food was tasty and the restaurant had a nice atmosphere. The service was friendly and efficient. I enjoyed my meal and would visit again.", created_at=random_date(start_date, end_date)),

        Review(user_id=15, restaurant_id=15, rating=5, comments="Ramen House offers delicious ramen meals that are both healthy and flavorful. The variety was impressive and the food was well-prepared. The atmosphere was inviting and the service was excellent. I highly recommend this place for ramen cuisine.", created_at=random_date(start_date, end_date)),
        Review(user_id=8, restaurant_id=15, rating=4, comments="Ramen House serves good ramen food with a range of options. The dishes were flavorful and the service was attentive. The restaurant had a cozy ambiance that made the meal enjoyable. It’s a great spot for ramen dining.", created_at=random_date(start_date, end_date)),
        Review(user_id=12, restaurant_id=15, rating=3, comments="Ramen House is decent but some dishes were just average. The food was healthy but lacked excitement in terms of flavors. The restaurant had a nice atmosphere and the service was okay. It’s a good option for ramen.", created_at=random_date(start_date, end_date)),
        Review(user_id=14, restaurant_id=15, rating=2, comments="Ramen House was underwhelming. The dishes were bland and didn’t have much flavor. The service was slow and the restaurant wasn’t very clean. I don’t think I’ll be returning based on my experience.", created_at=random_date(start_date, end_date)),
        Review(user_id=10, restaurant_id=15, rating=4, comments="Ramen House provides a good variety of ramen dishes. The food was tasty and the ambiance was pleasant. The service was friendly and the meal was enjoyable. I had a good experience and would recommend it.", created_at=random_date(start_date, end_date)),

        Review(user_id=4, restaurant_id=16, rating=5, comments="Deli Delight is a fantastic spot for a classic diner experience. The food was exactly what I was craving, with generous portions and great flavor. The staff was friendly and the atmosphere was cozy. I had a wonderful time and will definitely be coming back.", created_at=random_date(start_date, end_date)),
        Review(user_id=12, restaurant_id=16, rating=3, comments="Deli Delight is a decent diner with a variety of options. The food was okay, but some dishes were better than others. The service was acceptable, though not particularly memorable. It's a good place for a quick meal but not exceptional.", created_at=random_date(start_date, end_date)),
        Review(user_id=19, restaurant_id=16, rating=2, comments="Deli Delight didn’t impress me. The food lacked flavor and the service was slow. The ambiance was fine but didn’t make up for the disappointing meal. I’m not sure if I’ll return based on this experience.", created_at=random_date(start_date, end_date)),
        Review(user_id=7, restaurant_id=16, rating=4, comments="Deli Delight offers a good variety of diner classics. The food was tasty and the service was friendly. The restaurant had a nice, casual atmosphere that made for a pleasant meal. I enjoyed my visit and would come back.", created_at=random_date(start_date, end_date)),
        Review(user_id=17, restaurant_id=16, rating=5, comments="Deli Delight is an excellent choice for a hearty meal. The dishes were well-prepared and the flavors were spot on. The staff was welcoming and the setting was charming. It’s a great place to enjoy a classic diner experience.", created_at=random_date(start_date, end_date)),

        Review(user_id=11, restaurant_id=17, rating=4, comments="Bistro Bliss is a great spot for bistro lovers. The variety of dishes was impressive and the bistro was fresh. The restaurant had a pleasant atmosphere and the service was good. I had a satisfying meal and would return.", created_at=random_date(start_date, end_date)),
        Review(user_id=6, restaurant_id=17, rating=5, comments="Bistro Bliss serves some of the best bistro in town. The dishes were flavorful and well-presented. The ambiance was relaxed and the service was excellent. I highly recommend this place for a bistro fix.", created_at=random_date(start_date, end_date)),
        Review(user_id=13, restaurant_id=17, rating=3, comments="Bistro Bliss offers decent bistro but it didn’t blow me away. The dishes were okay and the service was average. The atmosphere was nice but didn’t make up for the lackluster food. It’s an okay choice for bistro.", created_at=random_date(start_date, end_date)),
        Review(user_id=15, restaurant_id=17, rating=2, comments="Bistro Bliss was disappointing. The bistro was not as fresh as expected and the service was slow. The restaurant was average but the meal didn’t meet my expectations. I wouldn’t recommend it based on my experience.", created_at=random_date(start_date, end_date)),
        Review(user_id=9, restaurant_id=17, rating=4, comments="Bistro Bliss has a good selection of bistro dishes. The flavors were good and the service was friendly. The atmosphere was pleasant and the meal was enjoyable. I had a good experience and would come back.", created_at=random_date(start_date, end_date)),

        Review(user_id=14, restaurant_id=18, rating=5, comments="Thai Terrace is fantastic for thai food enthusiasts. The patties were juicy and the toppings were fresh. The restaurant had a great atmosphere and the service was fast. I highly recommend this place for a great thai food experience.", created_at=random_date(start_date, end_date)),
        Review(user_id=10, restaurant_id=18, rating=4, comments="Thai Terrace serves excellent thai food with a variety of options. The flavors were rich and the portions were generous. The service was good and the setting was casual. I enjoyed my meal and would return.", created_at=random_date(start_date, end_date)),
        Review(user_id=18, restaurant_id=18, rating=3, comments="Thai Terrace is decent but didn’t exceed my expectations. The thai food was good but not extraordinary. The service was fine and the ambiance was casual. It’s an okay spot for a thai food but not exceptional.", created_at=random_date(start_date, end_date)),
        Review(user_id=12, restaurant_id=18, rating=2, comments="Thai Terrace was underwhelming. The thai food was average and the service was slow. The restaurant had a nice atmosphere but the meal didn’t impress me. I’m not sure if I’ll be coming back.", created_at=random_date(start_date, end_date)),
        Review(user_id=3, restaurant_id=18, rating=4, comments="Thai Terrace offers a good thai food experience with a variety of options. The food was tasty and the service was friendly. The restaurant had a nice vibe that made for a pleasant visit. I would recommend it for a Pad Thai craving.", created_at=random_date(start_date, end_date)),

        Review(user_id=16, restaurant_id=19, rating=5, comments="Crepe Corner is a must-visit for crepe lovers. The crepes were flavorful and the variety was impressive. The restaurant had a lively atmosphere and the service was excellent. I had a fantastic time and will definitely be returning.", created_at=random_date(start_date, end_date)),
        Review(user_id=5, restaurant_id=19, rating=4, comments="Crepe Corner provides a great selection of crepes. The taste was delicious and the service was prompt. The ambiance was vibrant and added to the experience. I enjoyed my delicious crepe and would recommend it.", created_at=random_date(start_date, end_date)),
        Review(user_id=14, restaurant_id=19, rating=3, comments="Crepe Corner is good but not the best. The crepes were decent but lacked some flavor. The service was okay and the restaurant had a casual atmosphere. It’s a decent spot for crepes but not outstanding.", created_at=random_date(start_date, end_date)),
        Review(user_id=13, restaurant_id=19, rating=2, comments="Crepe Corner was a bit of a letdown. The crepes were bland and the service was slow. The restaurant was average and didn’t offer much in terms of ambiance. I wouldn’t recommend it based on my experience.", created_at=random_date(start_date, end_date)),
        Review(user_id=19, restaurant_id=19, rating=4, comments="Crepe Corner offers a good crepe experience with flavorful options. The atmosphere was lively and the service was friendly. The crepes were enjoyable and the restaurant had a good vibe. I would visit again.", created_at=random_date(start_date, end_date)),

        Review(user_id=11, restaurant_id=20, rating=5, comments="Fish Fry is exceptional for seafood lovers. The quality of the fish was top-notch and the variety was impressive. The restaurant had a nice atmosphere and the service was attentive. I highly recommend it for a great seafood experience.", created_at=random_date(start_date, end_date)),
        Review(user_id=7, restaurant_id=20, rating=4, comments="Fish Fry serves delicious seafood with a good variety. The flavors were fresh and the presentation was great. The service was friendly and the ambiance was pleasant. I enjoyed my meal and would return.", created_at=random_date(start_date, end_date)),
        Review(user_id=15, restaurant_id=20, rating=3, comments="Fish Fry is decent but not exceptional. The seafood was good but didn’t stand out. The service was average and the restaurant had a nice ambiance. It’s an okay choice for seafood but not extraordinary.", created_at=random_date(start_date, end_date)),
        Review(user_id=2, restaurant_id=20, rating=2, comments="Fish Fry was disappointing. The seafood lacked flavor and the service was slow. The restaurant had a nice setting but didn’t make up for the underwhelming food. I’m not sure if I’ll return.", created_at=random_date(start_date, end_date)),
        Review(user_id=8, restaurant_id=20, rating=4, comments="Fish Fry provides a good seafood experience with fresh ingredients. The variety was nice and the service was good. The ambiance was relaxed and made for a pleasant meal. I had a positive experience and would recommend it.", created_at=random_date(start_date, end_date))

    ]

    db.session.bulk_save_objects(reviews)
    db.session.commit()

def undo_reviews():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.restaurants RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM reviews"))

    db.session.commit()
