"""empty message

Revision ID: 4953535fc86b
Revises: 1bb4fe1faf42
Create Date: 2024-08-12 09:23:53.031601

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '4953535fc86b'
down_revision = '1bb4fe1faf42'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### end Alembic commands ###
