"""empty message

Revision ID: 1bb4fe1faf42
Revises: 
Create Date: 2024-08-11 17:01:53.601436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb4fe1faf42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### end Alembic commands ###
