"""empty message

Revision ID: 1bb4fe1faf42
Revises: 38bdfe458578
Create Date: 2024-08-11 17:01:53.601436

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '1bb4fe1faf42'
down_revision = '38bdfe458578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### end Alembic commands ###
