"""empty message

Revision ID: 82cf50c0a8be
Revises: 33231d52a691
Create Date: 2024-08-15 01:23:01.383653

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '82cf50c0a8be'
down_revision = '33231d52a691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
        batch_op.alter_column('avg_rating',
               existing_type=sa.NUMERIC(precision=2, scale=1),
               nullable=True)
        batch_op.alter_column('day_of_week',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('avg_rating',
               existing_type=sa.NUMERIC(precision=2, scale=1),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)

    # ### end Alembic commands ###
