"""Seeder-Data-2.0

Revision ID: 87d276eefb2b
Revises: 4953535fc86b
Create Date: 2024-08-17 23:10:45.138826

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")



# revision identifiers, used by Alembic.
revision = '87d276eefb2b'
down_revision = '4953535fc86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sa.String(length=2001),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=2001),
               type_=sa.VARCHAR(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###
