"""8/17/2024, 11:24PM

Revision ID: 94235e089aea
Revises: 87d276eefb2b
Create Date: 2024-08-17 23:25:18.689143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94235e089aea'
down_revision = '87d276eefb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2001),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=2001),
               existing_nullable=True)

    # ### end Alembic commands ###
